# Generated by Django 2.2.19 on 2021-08-28 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                ('type_resource', models.TextField(choices=[('RE', 'Salle de réunion'), ('VI', 'Salle de visioconférence')], default='RE', max_length=2, verbose_name='Type de ressource')),
                ('location', models.CharField(max_length=100, verbose_name='Localisation')),
                ('capacity', models.IntegerField(verbose_name='Capacité')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Resource', verbose_name='Ressource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
